/**
 * 14 主星 Archetype 視覺數據
 * 每顆主星包含：視覺關鍵字、專屬配色、代表符號、人生課題
 */

export const ARCHETYPES = {
  '紫微': {
    id: 'zrw',
    archetype: '帝王型',
    symbol: '👑',
    color: '#c9a84c',
    tagline: '天生我才，眾星拱月',
    strength: '決斷力與號召力',
    weakness: '固執與控制欲',
    growthTask: '學會傾聽，不要凡事由自己說了算',
    idealEnv: '掌舵的位置、領導團隊、制定規則',
    avoid: '被架空權力的位置、被迫服從',
    colorCodes: ['#c9a84c', '#8b6914', '#2a2010'],
    quote: '你不需要證明自己是帝王，你只需要行動像帝王。'
  },
  '天機': {
    id: 'tjj',
    archetype: '謀略家',
    symbol: '🧠',
    color: '#5b8dd9',
    tagline: '算無遺策，深謀遠慮',
    strength: '分析力與策劃力',
    weakness: '過度思考導致行動延遲',
    growthTask: '想到80%就行動，不要等100%才動',
    idealEnv: '智庫、顧問、策略部門',
    avoid: '高壓決策前線、需要立即行動的環境',
    colorCodes: ['#5b8dd9', '#2a4a8b', '#0a1525'],
    quote: '最好的策略是那些想到80%就行動的人做出來的。'
  },
  '太陽': {
    id: 'tyy',
    archetype: '光之子',
    symbol: '☀️',
    color: '#e8b84a',
    tagline: '光熱照耀，萬物生長',
    strength: '社交力與名聲渴望',
    weakness: '過度在意他人眼光',
    growthTask: '在照亮別人之前，先確認自己是否還有燃料',
    idealEnv: '舞台中央、社交場合、公開演說',
    avoid: '長期隔離不被看見的工作',
    colorCodes: ['#e8b84a', '#b8860b', '#2a1f00'],
    quote: '你的光不需要所有人的認可，只需要照亮真正重要的時刻。'
  },
  '武曲': {
    id: 'wqx',
    archetype: '金剛型',
    symbol: '⚔️',
    color: '#8b7355',
    tagline: '剛毅不屈，財富為道',
    strength: '行動力與財務嗅覺',
    weakness: '不擅長示弱與求助',
    growthTask: '有時候退一步，是為了打更遠的仗',
    idealEnv: '金融領域、創業、武職',
    avoid: '需要大量情感溝通的角色',
    colorCodes: ['#8b7355', '#5a4a35', '#1a1510'],
    quote: '硬碰硬是勇氣，但知道什麼時候該軟，是智慧。'
  },
  '天同': {
    id: 'ttt',
    archetype: '療癒者',
    symbol: '🌿',
    color: '#7ab87a',
    tagline: '和光同塵，萬物得一以生',
    strength: '適應力與感受力',
    weakness: '缺乏邊界，容易被消耗',
    growthTask: '學會說不，是對自己最深的温柔',
    idealEnv: '藝術創作、陪伴型角色、諮詢',
    avoid: '高強度競爭環境',
    colorCodes: ['#7ab87a', '#3a6b3a', '#0a1a0a'],
    quote: '你對世界的温柔，不需要以失去自己為代價。'
  },
  '廉貞': {
    id: 'lzh',
    archetype: '烈焰型',
    symbol: '🔥',
    color: '#d94a4a',
    tagline: '敢愛敢恨，情如烈焰',
    strength: '感受力與情感穿透力',
    weakness: '情緒起伏大，執著難放',
    growthTask: '允許自己放下，不是失敗，是升級',
    idealEnv: '創意行業、情感工作者',
    avoid: '需要情緒高度穩定的工作',
    colorCodes: ['#d94a4a', '#8b2a2a', '#250a0a'],
    quote: '你的執著是你的燃料，也是你需要學會節制的火焰。'
  },
  '天府': {
    id: 'tfs',
    archetype: '倉儲型',
    symbol: '🏛️',
    color: '#9b8b6b',
    tagline: '天府之國，固若金湯',
    strength: '理財力與穩健力',
    weakness: '缺乏冒險精神，錯過機會',
    growthTask: '允許自己偶爾冒險，不冒險本身也是一種風險',
    idealEnv: '財務管理、傳統企業、房產',
    avoid: '需要快速轉型的環境',
    colorCodes: ['#9b8b6b', '#6b5a40', '#1a1510'],
    quote: '你的穩健是別人的依靠，但記得留一點冒險給自己。'
  },
  '太陰': {
    id: 'tyyin',
    archetype: '月神型',
    symbol: '🌙',
    color: '#b8c4d9',
    tagline: '月華如水，暗中滋養',
    strength: '觀察力與細節敏感度',
    weakness: '被動迴避衝突，不善表達需求',
    growthTask: '你的需求和別人的需求一樣重要',
    idealEnv: '幕後工作、獨立作業、藝術創作',
    avoid: '高對抗性談判場合',
    colorCodes: ['#b8c4d9', '#6b7a9b', '#151a25'],
    quote: '月光不需要太陽的讚美，月光本身就是一種美。'
  },
  '貪狼': {
    id: 'tll',
    archetype: '欲望探險家',
    symbol: '🎯',
    color: '#d94a8b',
    tagline: '貪而不知足，狼行千里',
    strength: '社交力與慾望驅動力',
    weakness: '慾望過多，精力分散',
    growthTask: '一次只專注一個目標，是對自己最大的仁慈',
    idealEnv: '社交場合、談判、娛樂產業',
    avoid: '需要長期單一專注的工作',
    colorCodes: ['#d94a8b', '#8b2a5a', '#250a15'],
    quote: '你的飢餓感是你的引擎，但學會品嚐是升級。'
  },
  '巨門': {
    id: 'jmk',
    archetype: '真相探索者',
    symbol: '🔍',
    color: '#8b8b9b',
    tagline: '門後有真相，但也有風險',
    strength: '分析力與洞察力',
    weakness: '過度懷疑，口語傷人',
    growthTask: '在說出口之前，先問自己：這句話是為了我，還是為了他？',
    idealEnv: '研究崗位、調查報導、法律',
    avoid: '高度需要團隊和諧的環境',
    colorCodes: ['#8b8b9b', '#5a5a6b', '#15151a'],
    quote: '你的懷疑是通向真相的橋，但不要停在橋上不走。'
  },
  '天相': {
    id: 'txx',
    archetype: '協調者',
    symbol: '⚖️',
    color: '#7ab8d9',
    tagline: '天為之相，調和其他',
    strength: '協調力與服務精神',
    weakness: '過度配合，缺乏主見',
    growthTask: '你的價值不是當和事佬，而是當有原則的橋',
    idealEnv: '行政、後勤、項目管理',
    avoid: '需要獨斷決策的位置',
    colorCodes: ['#7ab8d9', '#3a6b8b', '#0a1a25'],
    quote: '配合是美德，但失去自己的配合，只是逃避。'
  },
  '天梁': {
    id: 'tll2',
    archetype: '守護者',
    symbol: '🛡️',
    color: '#b8a87a',
    tagline: '天梁蔭庇，庇護眾生',
    strength: '照顧力與穩定力',
    weakness: '愛說教、過度保護',
    growthTask: '放下「我都是為你好」，允許別人走自己的彎路',
    idealEnv: '公益事業、醫療、教育',
    avoid: '被照顧者不領情的環境',
    colorCodes: ['#b8a87a', '#8b7a4a', '#251f10'],
    quote: '守護是恩情，但不要讓守護變成一種控制。'
  },
  '七殺': {
    id: 'zsh',
    archetype: '破局者',
    symbol: '💥',
    color: '#d97a4a',
    tagline: '七殺過境，寸草不生',
    strength: '突破力與逆境韌性',
    weakness: '魯莽、缺乏長期規劃',
    growthTask: '在爆發之前，先給自己三秒鐘評估後果',
    idealEnv: '急需突破的環境、危機處理',
    avoid: '需要長期累積潤滑的領域',
    colorCodes: ['#d97a4a', '#8b4a2a', '#250f05'],
    quote: '你的破局能力是你最鋒利的武器，也是最需要節制的力量。'
  },
  '破軍': {
    id: 'pjj',
    archetype: '變革者',
    symbol: '🌀',
    color: '#7a5bd9',
    tagline: '破舊立新，混沌為始',
    strength: '破局力與不畏懼改變',
    weakness: '不穩定，難以堅持',
    growthTask: '破局的意義是為了更好的重建，不是為了破而破',
    idealEnv: '創業、變革項目、創意產業',
    avoid: '需要高度可預測性的環境',
    colorCodes: ['#7a5bd9', '#4a2a8b', '#0f0525'],
    quote: '你敢於打破一切，但記得留下一個確定的自己。'
  }
};
